name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Ensure this version matches your project requirements

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: python -c "import os; os.system('dotnet test TvMazeScraper.sln --configuration Release --no-build --verbosity normal  --logger trx');"  
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      with:
        name: 'Test Results'
        path: '**/TestResults/**/*.trx'
        reporter: 'dotnet-trx'      
